import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconUsers,
  IconUserCheck,
  IconActivity,
  IconCoins,
  IconShoppingCart,
  IconTrendingUp,
  IconLink,
  IconGift,
  IconStar,
  IconTrophy,
  IconRepeat,
  IconWallet,
  IconReceipt,
  IconCashBanknote,
  IconCircleCheck,
  IconChartBar,
  IconChartPie,
  IconChartLine,
  IconCurrencyDollar,
  IconMessage,
  IconBell,
  IconDeviceMobile,
  IconUserCog,
  IconShield,
  IconPlug,
  IconAdjustments
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  users: IconUsers,
  userCheck: IconUserCheck,
  activity: IconActivity,
  coins: IconCoins,
  shoppingCart: IconShoppingCart,
  trendingUp: IconTrendingUp,
  link: IconLink,
  gift: IconGift,
  star: IconStar,
  trophy: IconTrophy,
  repeat: IconRepeat,
  wallet: IconWallet,
  creditCard: IconCreditCard,
  receipt: IconReceipt,
  banknote: IconCashBanknote,
  checkCircle: IconCircleCheck,
  barChart: IconChartBar,
  pieChart: IconChartPie,
  lineChart: IconChartLine,
  dollarSign: IconCurrencyDollar,
  messageSquare: IconMessage,
  bell: IconBell,
  smartphone: IconDeviceMobile,
  fileText: IconFileText,
  userCog: IconUserCog,
  shield: IconShield,
  plug: IconPlug,
  sliders: IconAdjustments
};
